apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-churn-api
  labels:
    app: customer-churn-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-churn-api
  template:
    metadata:
      labels:
        app: customer-churn-api
    spec:
      containers:
        - name: customer-churn-api
          image: customer-churn-api:1.1
          imagePullPolicy: Never
          ports:
            - containerPort: 8000