apiVersion: v1
kind: Service
metadata:
  name: customer-churn-api-service
spec:
  selector:
    app: customer-churn-api
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: NodePort